### PR TITLE
updated metadata.json

### PR DESCRIPTION
**Pull request by cjestel**

### CODE REVIEW

**Comment by adamcstephens** [comment]
Are we actually testing this against Ubuntu?

**Comment by cjestel** [comment]
I have not tested it but preserved the original code base as much as possible. Should I remove that from the supported but leave the code in and accept PR's?

**Comment by adamcstephens** [comment]
This won't work on Ubuntu/Debian:

https://github.com/covermymeds/puppet-pgbouncer/blob/master/manifests/init.pp#L96

I'd either remove it from metadata, or explicitly state in the README that there is some support for Ubuntu but we don't test it and it may need fixing through PRs

**Comment by cjestel** [comment]
That is listed under the limitations section of the readme. I fixed a typo in that section and added some more words to it to clarify. It's added to this PR.

**Comment by adamcstephens** [comment]
Looks good. :shipit:

**Pull request merged**
